### PR TITLE
[FEATURE]: added run to public api for complex scenarios

### PR DESCRIPTION
**Pull request by toranb**
One way to handle the issue raised in #18 (more documentation than anything but I did expose the `run` method previously not available)

@cklimkowsky please give this a look /pull it down and use it in the browser to see if this acts as you expect.

### CODE REVIEW

**Comment by caseklim** [comment]
@toranb thank you for such a fast response with this!

I took a look at the tests you wrote and am now using `run` as follows in my application:

```
radeoValidation: Ember.computed("model.radeo", "model.tos", function() {
  return run(this.get("model.radeo"), customFunc, this);
}),
```

If this is how I should be defining complex validation use cases (`Ember.computed` and `run` instead of `validate`) then it seems to be working! Although I'm surprised `validate` (which seems to just wrap `run`) didn't work in this manner before... is it because `validate` only takes a single field?

**Comment by caseklim** [comment]
Hm, one more thing I found is that array values aren't re-validated. Is there a way to use `validateEach` not in the context of an `ArrayController` or to validate that an array isn't empty?

**Comment by toranb** [comment]
@cklimkowsky great point - I'll see if I can add an ArrayController validation in this PR to show how the validateEach would work in this scenario.

**Comment by toranb** [comment]
@cklimkowsky one question I had for you before I dive in and get this solid in the coming week

if you pull this branch, run `ember s` in the root and open the browser to visit `http://localhost:4200/complex`

You should see the "complex form" I used in that acceptance test. Could you confirm the UX is as you expect in this "more complicated" validation? I assumed a lot putting this together and wanted to see if you could provide feedback /or confirm what I have is what you need.

Thank you in advance!

**Comment by caseklim** [comment]
@toranb yes, I would say that UI is in line with the example I described. Thanks again for continuing to help with this :)

I've been playing around a bit on my end too, and it seems the root of the problem is that the "other" dependent fields (not the primary field we're validating) when changed weren't changing the validation

I came up with this, which validates against multiple fields:

```
const validate = (...args) => {
  let options;

  if (typeof args[args.length - 1] === 'function') {
    options = args.pop();
  }

  const computedProperty = Ember.computed(function() {
    const value = this.getWithDefault(args[0], '');
    return run(value, options, this);
  });

  return computedProperty.property.apply(computedProperty, args);
};
```

Which can then be used as `validate(propertyName)` or `validate(propertyName1, propertyName2, function() { ... });`

In regards to arrays, I realized I could pass `model.propertyName.[]` into validate and it's now able to detect when elements are added and removed

**Comment by toranb** [comment]
@cklimkowsky wow this is some great work! I took what you suggested and tweaked it a bit to get the test suite passing (turns out I support both functions and regex so I had to go w/ a not equal string conditional).

This look solid from your perspective? I've got a passing build at the moment - I'll need to write up a test for the ArrayController version but I feel good about this so far. I'll see if I can find some time later in the week to get the Array version up/ and confirmed. Thanks again for the collaboration !!!

**Comment by caseklim** [comment]
@toranb ooh right, good catch with the function vs. regex! LGTM with one question, does the ES6 syntax work for you? We have Babel set up for our app

**Comment by toranb** [comment]
The ES6 syntax is cool here because it's an ember-cli addon and truthfully I've only ever consumed it in that way. I feel good about the base validation changes you made/and it's all test driven but when I wrote the ArrayController version last night I still feel this isn't a greatly supported use case. What I had was a validateEach w/ 2 fields (to mirror what we did with validate) but that is far from solid. You mentioned something above about your work on the array side of this - did you have a code snippet of what your component/ or controller looked like using validateEach?

**Comment by toranb** [comment]
@cklimkowsky just a heads up - back on this project after a full week out and I'm making progress on the Array requirement. I'll likely keep pluging away at it until I get something mostly working -then I'll push it up and get some feedback. Thanks for the patience

**Pull request closed without merging**
